# Generated by Django 4.0 on 2022-02-21 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('agency_id', models.CharField(max_length=140, primary_key=True, serialize=False)),
                ('agency_name', models.CharField(default='', max_length=140)),
                ('agency_url', models.CharField(default='', max_length=140)),
                ('agency_timezone', models.CharField(default='Europe/Paris', max_length=140)),
                ('agency_lang', models.CharField(default='fr', max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('service_id', models.CharField(max_length=140, primary_key=True, serialize=False)),
                ('monday', models.CharField(default='0', max_length=1)),
                ('tuesday', models.CharField(default='0', max_length=1)),
                ('wednesday', models.CharField(default='0', max_length=1)),
                ('thursday', models.CharField(default='0', max_length=1)),
                ('friday', models.CharField(default='0', max_length=1)),
                ('saturday', models.CharField(default='0', max_length=1)),
                ('sunday', models.CharField(default='0', max_length=1)),
                ('start_date', models.CharField(default='YYYYDDMM', max_length=8)),
                ('end_date', models.CharField(default='YYYYDDMM', max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Routes',
            fields=[
                ('route_id', models.CharField(max_length=140, primary_key=True, serialize=False)),
                ('route_short_name', models.CharField(default='', max_length=140)),
                ('route_long_name', models.CharField(default='', max_length=140)),
                ('route_desc', models.CharField(default='', max_length=140)),
                ('route_type', models.CharField(default='', max_length=140)),
                ('route_url', models.CharField(default='', max_length=140)),
                ('route_color', models.CharField(default='', max_length=6)),
                ('route_text_color', models.CharField(default='', max_length=6)),
                ('agency_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.agency')),
            ],
        ),
        migrations.CreateModel(
            name='Shapes',
            fields=[
                ('shape_id', models.CharField(max_length=140, primary_key=True, serialize=False)),
                ('shape_pt_lon', models.CharField(default='', max_length=140)),
                ('shape_pt_lat', models.CharField(default='', max_length=140)),
                ('shape_pt_sequence', models.CharField(default='0', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Stop_extensions',
            fields=[
                ('object_id', models.CharField(max_length=140, primary_key=True, serialize=False)),
                ('object_system', models.CharField(default='', max_length=140)),
                ('object_code', models.CharField(default='', max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='Stops',
            fields=[
                ('stop_id', models.CharField(max_length=140, primary_key=True, serialize=False)),
                ('stop_name', models.CharField(default='', max_length=140)),
                ('stop_desc', models.CharField(default='', max_length=140)),
                ('stop_lat', models.CharField(default='', max_length=140)),
                ('stop_lon', models.CharField(default='', max_length=140)),
                ('zone_id', models.CharField(default='', max_length=140)),
                ('stop_url', models.CharField(default='', max_length=140)),
                ('location_type', models.CharField(default='', max_length=1)),
                ('parent_station', models.CharField(default='', max_length=140)),
                ('wheelchair_boarding', models.CharField(default='', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Trips',
            fields=[
                ('trip_id', models.CharField(max_length=140, primary_key=True, serialize=False)),
                ('trip_headsign', models.CharField(default='', max_length=140)),
                ('trip_short_name', models.CharField(default='', max_length=140)),
                ('direction_id', models.CharField(default='', max_length=140)),
                ('block_id', models.CharField(default='', max_length=140)),
                ('wheelchair_accessible', models.CharField(default='', max_length=1)),
                ('bikes_allowed', models.CharField(default='', max_length=1)),
                ('trip_desc', models.CharField(default='', max_length=140)),
                ('route_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.routes')),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.calendar')),
                ('shape_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.shapes')),
            ],
        ),
        migrations.CreateModel(
            name='Transfers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_type', models.CharField(default='2', max_length=1)),
                ('min_transfer_time', models.CharField(default='', max_length=3)),
                ('from_stop_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='stop_id_from', to='app.stops')),
                ('to_stop_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='stop_id_to', to='app.stops')),
            ],
        ),
        migrations.CreateModel(
            name='Stop_times',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_time', models.TimeField(default='00:00:00')),
                ('departure_time', models.TimeField(default='00:00:00')),
                ('stop_sequence', models.CharField(default='', max_length=140)),
                ('stop_time_desc', models.CharField(default='', max_length=1)),
                ('pickup_type', models.CharField(default='', max_length=1)),
                ('drop_off_type', models.CharField(default='', max_length=1)),
                ('stop_id', models.ForeignKey(default='DEFAULT', on_delete=django.db.models.deletion.CASCADE, to='app.stops')),
                ('trip_id', models.ForeignKey(default='DEFAULT', on_delete=django.db.models.deletion.CASCADE, to='app.trips')),
            ],
        ),
        migrations.CreateModel(
            name='Calendar_dates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(default='YYYYDDMM', max_length=8)),
                ('exception_type', models.CharField(default='1', max_length=1)),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.calendar')),
            ],
        ),
    ]
