# Generated by Django 4.0 on 2022-02-21 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_id', models.CharField(default='', max_length=140)),
                ('agency_name', models.CharField(default='', max_length=140)),
                ('agency_url', models.CharField(default='', max_length=140)),
                ('agency_timezone', models.CharField(default='Europe/Paris', max_length=140)),
                ('agency_lang', models.CharField(default='fr', max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.CharField(default='', max_length=140)),
                ('monday', models.CharField(default='0', max_length=1)),
                ('tuesday', models.CharField(default='0', max_length=1)),
                ('wednesday', models.CharField(default='0', max_length=1)),
                ('thursday', models.CharField(default='0', max_length=1)),
                ('friday', models.CharField(default='0', max_length=1)),
                ('saturday', models.CharField(default='0', max_length=1)),
                ('sunday', models.CharField(default='0', max_length=1)),
                ('start_date', models.CharField(default='20000101', max_length=6)),
                ('end_date', models.CharField(default='20000101', max_length=6)),
            ],
        ),
    ]
