# Generated by Django 4.0 on 2022-02-21 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agency',
            name='id',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='id',
        ),
        migrations.AlterField(
            model_name='agency',
            name='agency_id',
            field=models.CharField(max_length=140, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='end_date',
            field=models.CharField(default='YYYYDDMM', max_length=8),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='service_id',
            field=models.CharField(max_length=140, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='start_date',
            field=models.CharField(default='YYYYDDMM', max_length=8),
        ),
        migrations.CreateModel(
            name='Calendar_dates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(default='YYYYDDMM', max_length=8)),
                ('exception_type', models.CharField(default='1', max_length=1)),
                ('service_id', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='app.calendar')),
            ],
        ),
    ]
