# Generated by Django 4.0.1 on 2022-03-02 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZipUrl',
            fields=[
                ('zipurl_id', models.CharField(max_length=140, primary_key=True, serialize=False)),
                ('zipurl_value', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
