# Generated by Django 4.0 on 2022-02-21 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_agency_id_remove_calendar_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar_dates',
            name='service_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.calendar'),
        ),
    ]
