# Generated by Django 4.0.1 on 2022-03-02 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_zipurl_zipurl_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zipurl',
            name='zipurl_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
