# Generated by Django 4.0.1 on 2022-03-03 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_zipurl_zipurl_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routes',
            name='agency_id',
            field=models.CharField(default='', max_length=140),
        ),
        migrations.AlterField(
            model_name='stop_times',
            name='stop_id',
            field=models.CharField(default='', max_length=140),
        ),
        migrations.AlterField(
            model_name='stop_times',
            name='trip_id',
            field=models.CharField(default='', max_length=140),
        ),
        migrations.AlterField(
            model_name='transfers',
            name='from_stop_id',
            field=models.CharField(default='', max_length=140),
        ),
        migrations.AlterField(
            model_name='transfers',
            name='to_stop_id',
            field=models.CharField(default='', max_length=140),
        ),
        migrations.AlterField(
            model_name='trips',
            name='route_id',
            field=models.CharField(default='', max_length=140),
        ),
        migrations.AlterField(
            model_name='trips',
            name='service_id',
            field=models.CharField(default='', max_length=140),
        ),
        migrations.AlterField(
            model_name='trips',
            name='shape_id',
            field=models.CharField(default='', max_length=140),
        ),
    ]
