# Generated by Django 4.0.1 on 2022-03-03 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_routes_agency_id_alter_stop_times_stop_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar_dates',
            name='id',
            field=models.BigAutoField(auto_created=True, default=int, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='calendar_dates',
            name='date',
            field=models.CharField(default='YYYYDDMM', max_length=8),
        ),
    ]
