# Generated by Django 4.0.1 on 2022-03-03 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_calendar_dates_id_alter_calendar_dates_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='shapes',
            name='id',
            field=models.BigAutoField(auto_created=True, default=int, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shapes',
            name='shape_id',
            field=models.CharField(max_length=140),
        ),
    ]
