# Generated by Django 4.0.1 on 2022-03-03 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_shapes_id_alter_shapes_shape_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='stop_extensions',
            name='id',
            field=models.BigAutoField(auto_created=True, default=int, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stop_extensions',
            name='object_id',
            field=models.CharField(max_length=140),
        ),
    ]
