# Generated by Django 4.0.1 on 2022-03-04 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_stop_extensions_id_alter_stop_extensions_object_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stop_times',
            name='arrival_time',
            field=models.CharField(default='', max_length=140),
        ),
        migrations.AlterField(
            model_name='stop_times',
            name='departure_time',
            field=models.CharField(default='', max_length=140),
        ),
    ]
